/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Storage } from './storage';


export interface Bin { 
    uuId?: number;
    binNumber?: string;
    storage?: Storage;
}

