/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sender } from './sender';
import { Message } from './message';
import { Recipient } from './recipient';


export interface MessageEvent { 
    app_id?: string;
    sender?: Sender;
    user_id_by_app?: string;
    recipient?: Recipient;
    event_name?: string;
    message?: Message;
    timestamp?: string;
}

