/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Size { 
    id?: number;
    code?: string;
    sizeLabel?: string;
    description?: string;
    region?: string;
}

