/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Storage } from './storage';
import { Bin } from './bin';
import { Product } from './product';


export interface InventoryRequest { 
    productList?: Array<Product>;
    storage?: Storage;
    bin?: Bin;
}

