/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductImage { 
    id?: number;
    fileName?: string;
    contentType?: string;
    fileData?: string;
    product?: Product;
}

