/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Neckline } from './neckline';
import { Occasion } from './occasion';
import { ProductImage } from './productImage';
import { Size } from './size';
import { Color } from './color';
import { SleeveLength } from './sleeveLength';
import { Brand } from './brand';
import { Type } from './type';
import { SeasonCode } from './seasonCode';
import { Shoulder } from './shoulder';
import { Style } from './style';
import { Tag } from './tag';


export interface Product { 
    productId?: number;
    productName?: string;
    category?: Category;
    type?: Type;
    color?: Color;
    size?: Size;
    style?: Style;
    sleeveLength?: SleeveLength;
    tag?: Tag;
    shoulder?: Shoulder;
    neckline?: Neckline;
    occasion?: Occasion;
    seasonCode?: SeasonCode;
    brand?: Brand;
    price?: number;
    images?: Array<ProductImage>;
    description?: string;
}

