/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductDTO { 
    productId?: number;
    productName?: string;
    description?: string;
    price?: number;
    category?: string;
    type?: string;
    color?: string;
    size?: string;
    style?: string;
    neckline?: string;
    sleeveLength?: string;
    tag?: string;
    shoulder?: string;
    brand?: string;
    occasion?: string;
    season?: string;
    imageUrls?: Array<string>;
}

