export * from './attributesController.service';
import { AttributesControllerService } from './attributesController.service';
export * from './binController.service';
import { BinControllerService } from './binController.service';
export * from './cabinetController.service';
import { CabinetControllerService } from './cabinetController.service';
export * from './contactController.service';
import { ContactControllerService } from './contactController.service';
export * from './inventoryController.service';
import { InventoryControllerService } from './inventoryController.service';
export * from './locationController.service';
import { LocationControllerService } from './locationController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './storageController.service';
import { StorageControllerService } from './storageController.service';
export * from './webhookController.service';
import { WebhookControllerService } from './webhookController.service';
export const APIS = [AttributesControllerService, BinControllerService, CabinetControllerService, ContactControllerService, InventoryControllerService, LocationControllerService, ProductControllerService, StorageControllerService, WebhookControllerService];
